houseData <- read.csv2("household_power_consumption.txt", colClasses = "character", na.strings = "?")
houseData <- subset(houseData, Date == "1/2/2007"|Date == "2/2/2007", select = Date:Sub_metering_3)
houseData$Sub_metering_1 <- as.numeric(houseData$Sub_metering_1)
houseData$Sub_metering_2 <- as.numeric(houseData$Sub_metering_2)
houseData$Sub_metering_3 <- as.numeric(houseData$Sub_metering_3)
houseData$Global_active_power <- as.numeric(houseData$Global_active_power)
houseData$Global_reactive_power <- as.numeric(houseData$Global_reactive_power)
houseData$Voltage <- as.numeric(houseData$Voltage)
datetime <- as.POSIXct(paste(houseData$Date, houseData$Time), format = "%d/%m/%Y %H:%M:%S")

png(filename = "plot4.png")
par(mfrow = c(2,2))
par(mar = c(4,4,2,2))
plot(datetime, houseData$Global_active_power, type = "l", ylab = "Global Active Power (killowatts)", xlab = '')
plot(datetime, houseData$Voltage, type = 'l', ylab = 'Voltage')
with(houseData, plot(datetime, Sub_metering_1, type = 'l', ylab = "Energy sub metering", xlab = ''))
lines(datetime, houseData$Sub_metering_2, col = "red")
lines(datetime, houseData$Sub_metering_3, col = 'blue')
legend(x = "topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1 )
plot(datetime, houseData$Global_reactive_power, type = 'l', ylab = "Global_reactive_power")
dev.off()